version: '2'

services:
  cassandra-node1:
    image: bitnami/cassandra:4.1.0
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=3072M
#    volumes:
#      - ./cassandra/conf/:/bitnami/cassandra/conf/

  cassandra-node2:
    image: bitnami/cassandra:4.1.0
    container_name: cassandra-node2
    ports:
      - "9043:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=3072M
#    volumes:
#      - ./cassandra/conf/:/bitnami/cassandra/conf/

  cassandra-node3:
    image: bitnami/cassandra:4.1.0
    container_name: cassandra-node3
    ports:
      - "9044:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2
      - CASSANDRA_AUTHENTICATOR=AllowAllAuthenticator
      - CASSANDRA_AUTHORIZER=AllowAllAuthorizer
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=3072M
#    volumes:
#      - ./cassandra/conf/:/bitnami/cassandra/conf/
